language: go

before_script:
    - export PATH=$HOME/gopath/bin:$PATH

jobs:
  include:
    - stage: Build and Test
      script:
        - make install.tools
        - make verify
        - make binaries
        - make test
      go: "1.10.x"
