//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-SNAPSHOT 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 05:46:02 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:emergency:cap:1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package oasis.names.tc.emergency.cap._1;
